-- premake5.lua
project "assimp"
	kind "StaticLib"
	language "C++"
	staticruntime "on"

	targetdir ("build/" .. outputdir .. "/%{prj.name}")
	objdir ("obj/" .. outputdir .. "/%{prj.name}")

	files
	{
		"include/assimp/",
		"include/assimp/anim.h",
		"include/assimp/aabb.h",
		"include/assimp/ai_assert.h",
		"include/assimp/camera.h",
		"include/assimp/color4.h",
		"include/assimp/color4.inl",
		"include/assimp/ColladaMetaData.h",
		"include/assimp/commonMetaData.h",
		"include/assimp/defs.h",
		"include/assimp/cfileio.h",
		"include/assimp/light.h",
		"include/assimp/material.h",
		"include/assimp/material.inl",
		"include/assimp/matrix3x3.h",
		"include/assimp/matrix3x3.inl",
		"include/assimp/matrix4x4.h",
		"include/assimp/matrix4x4.inl",
		"include/assimp/mesh.h",
		"include/assimp/ObjMaterial.h",
		"include/assimp/pbrmaterial.h",
		"include/assimp/GltfMaterial.h",
		"include/assimp/postprocess.h",
		"include/assimp/quaternion.h",
		"include/assimp/quaternion.inl",
		"include/assimp/scene.h",
		"include/assimp/metadata.h",
		"include/assimp/texture.h",
		"include/assimp/types.h",
		"include/assimp/vector2.h",
		"include/assimp/vector2.inl",
		"include/assimp/vector3.h",
		"include/assimp/vector3.inl",
		"include/assimp/version.h",
		"include/assimp/cimport.h",
		"include/assimp/importerdesc.h",
		"include/assimp/Importer.hpp",
		"include/assimp/DefaultLogger.hpp",
		"include/assimp/ProgressHandler.hpp",
		"include/assimp/IOStream.hpp",
		"include/assimp/IOSystem.hpp",
		"include/assimp/Logger.hpp",
		"include/assimp/LogStream.hpp",
		"include/assimp/NullLogger.hpp",
		"include/assimp/cexport.h",
		"include/assimp/Exporter.hpp",
		"include/assimp/DefaultIOStream.h",
		"include/assimp/DefaultIOSystem.h",
		"include/assimp/ZipArchiveIOSystem.h",
		"include/assimp/SceneCombiner.h",
		"include/assimp/fast_atof.h",
		"include/assimp/qnan.h",
		"include/assimp/BaseImporter.h",
		"include/assimp/Hash.h",
		"include/assimp/MemoryIOWrapper.h",
		"include/assimp/ParsingUtils.h",
		"include/assimp/StreamReader.h",
		"include/assimp/StreamWriter.h",
		"include/assimp/StringComparison.h",
		"include/assimp/StringUtils.h",
		"include/assimp/SGSpatialSort.h",
		"include/assimp/GenericProperty.h",
		"include/assimp/SpatialSort.h",
		"include/assimp/SkeletonMeshBuilder.h",
		"include/assimp/SmallVector.h",
		"include/assimp/SmoothingGroups.h",
		"include/assimp/SmoothingGroups.inl",
		"include/assimp/StandardShapes.h",
		"include/assimp/RemoveComments.h",
		"include/assimp/Subdivision.h",
		"include/assimp/Vertex.h",
		"include/assimp/LineSplitter.h",
		"include/assimp/TinyFormatter.h",
		"include/assimp/Profiler.h",
		"include/assimp/LogAux.h",
		"include/assimp/Bitmap.h",
		"include/assimp/XMLTools.h",
		"include/assimp/IOStreamBuffer.h",
		"include/assimp/CreateAnimMesh.h",
		"include/assimp/XmlParser.h",
		"include/assimp/BlobIOSystem.h",
		"include/assimp/MathFunctions.h",
		"include/assimp/Exceptional.h",
		"include/assimp/ByteSwapper.h",
		"include/assimp/Base64.hpp",
		"code/Common/Assimp.cpp",
		"code/Common/res/assimp.rc",
		"include/assimp/DefaultLogger.hpp",
		"include/assimp/LogStream.hpp",
		"include/assimp/Logger.hpp",
		"include/assimp/NullLogger.hpp",
		"code/Common/Win32DebugLogStream.h",
		"code/Common/DefaultLogger.cpp",
		"code/Common/FileLogStream.h",
		"code/Common/StdOStreamLogStream.h",
		"code/Common/Compression.cpp",
		"code/Common/Compression.h",
		"code/Common/BaseImporter.cpp",
		"code/Common/BaseProcess.cpp",
		"code/Common/BaseProcess.h",
		"code/Common/Importer.h",
		"code/Common/ScenePrivate.h",
		"code/Common/PostStepRegistry.cpp",
		"code/Common/ImporterRegistry.cpp",
		"code/Common/DefaultProgressHandler.h",
		"code/Common/DefaultIOStream.cpp",
		"code/Common/IOSystem.cpp",
		"code/Common/DefaultIOSystem.cpp",
		"code/Common/ZipArchiveIOSystem.cpp",
		"code/Common/PolyTools.h",
		"code/Common/Importer.cpp",
		"code/Common/IFF.h",
		"code/Common/SGSpatialSort.cpp",
		"code/Common/VertexTriangleAdjacency.cpp",
		"code/Common/VertexTriangleAdjacency.h",
		"code/Common/SpatialSort.cpp",
		"code/Common/SceneCombiner.cpp",
		"code/Common/ScenePreprocessor.cpp",
		"code/Common/ScenePreprocessor.h",
		"code/Common/SkeletonMeshBuilder.cpp",
		"code/Common/StandardShapes.cpp",
		"code/Common/TargetAnimation.cpp",
		"code/Common/TargetAnimation.h",
		"code/Common/RemoveComments.cpp",
		"code/Common/Subdivision.cpp",
		"code/Common/scene.cpp",
		"code/Common/Bitmap.cpp",
		"code/Common/Version.cpp",
		"code/Common/CreateAnimMesh.cpp",
		"code/Common/simd.h",
		"code/Common/simd.cpp",
		"code/Common/material.cpp",
		"code/Common/AssertHandler.cpp",
		"code/Common/Exceptional.cpp",
		"code/Common/Base64.cpp",
		"code/CApi/CInterfaceIOWrapper.cpp",
		"code/CApi/CInterfaceIOWrapper.h",
		"code/AssetLib/STEPParser/STEPFileReader.h",
		"code/AssetLib/STEPParser/STEPFileReader.cpp",
		"code/AssetLib/STEPParser/STEPFileEncoding.cpp",
		"code/AssetLib/STEPParser/STEPFileEncoding.h",
		"code/AssetLib/AMF/AMFImporter.hpp",
		"code/AssetLib/AMF/AMFImporter_Node.hpp",
		"code/AssetLib/AMF/AMFImporter.cpp",
		"code/AssetLib/AMF/AMFImporter_Geometry.cpp",
		"code/AssetLib/AMF/AMFImporter_Material.cpp",
		"code/AssetLib/AMF/AMFImporter_Postprocess.cpp",
		"code/AssetLib/3DS/3DSConverter.cpp",
		"code/AssetLib/3DS/3DSHelper.h",
		"code/AssetLib/3DS/3DSLoader.cpp",
		"code/AssetLib/3DS/3DSLoader.h",
		"code/AssetLib/AC/ACLoader.cpp",
		"code/AssetLib/AC/ACLoader.h",
		"code/AssetLib/Obj/ObjFileData.h",
		"code/AssetLib/Obj/ObjFileImporter.cpp",
		"code/AssetLib/Obj/ObjFileImporter.h",
		"code/AssetLib/Obj/ObjFileMtlImporter.cpp",
		"code/AssetLib/Obj/ObjFileMtlImporter.h",
		"code/AssetLib/Obj/ObjFileParser.cpp",
		"code/AssetLib/Obj/ObjFileParser.h",
		"code/AssetLib/Obj/ObjTools.h",
		"code/AssetLib/FBX/FBXImporter.cpp",
		"code/AssetLib/FBX/FBXCompileConfig.h",
		"code/AssetLib/FBX/FBXImporter.h",
		"code/AssetLib/FBX/FBXParser.cpp",
		"code/AssetLib/FBX/FBXParser.h",
		"code/AssetLib/FBX/FBXTokenizer.cpp",
		"code/AssetLib/FBX/FBXTokenizer.h",
		"code/AssetLib/FBX/FBXImportSettings.h",
		"code/AssetLib/FBX/FBXConverter.h",
		"code/AssetLib/FBX/FBXConverter.cpp",
		"code/AssetLib/FBX/FBXUtil.h",
		"code/AssetLib/FBX/FBXUtil.cpp",
		"code/AssetLib/FBX/FBXDocument.h",
		"code/AssetLib/FBX/FBXDocument.cpp",
		"code/AssetLib/FBX/FBXProperties.h",
		"code/AssetLib/FBX/FBXProperties.cpp",
		"code/AssetLib/FBX/FBXMeshGeometry.h",
		"code/AssetLib/FBX/FBXMeshGeometry.cpp",
		"code/AssetLib/FBX/FBXMaterial.cpp",
		"code/AssetLib/FBX/FBXModel.cpp",
		"code/AssetLib/FBX/FBXAnimation.cpp",
		"code/AssetLib/FBX/FBXNodeAttribute.cpp",
		"code/AssetLib/FBX/FBXDeformer.cpp",
		"code/AssetLib/FBX/FBXBinaryTokenizer.cpp",
		"code/AssetLib/FBX/FBXDocumentUtil.cpp",
		"code/AssetLib/FBX/FBXCommon.h",
	}

	includedirs
	{
		"include",
		"code",
		"contrib/stub",
		"contrib/unzip",
		"contrib",
		"contrib/pugixml/src",
		"contrib/zlib"
	}

	filter "system:windows"
		systemversion "latest"
		cppdialect "C++17"

		files
		{
		}

	filter "system:linux"
		-- https://github.com/premake/premake-core/wiki/pic
		pic "On"
		buildoptions "-std=c++11"
		systemversion "latest"

		files
		{
		}

	filter "configurations:Debug"
		runtime "Debug"
		symbols "on"

	filter "configurations:Release"
		runtime "Release"
		optimize "on"
